# Generated by Django 2.0 on 2020-07-13 11:35

from django.db import migrations, models
import django_unixdatetimefield.fields
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[(restapi.models.EventChoice('BUTTON_CLICKED'), 'BUTTON_CLICKED'), (restapi.models.EventChoice('LINK_CLICKED'), 'LINK_CLICKED'), (restapi.models.EventChoice('WINDOW_CLOSED'), 'WINDOW_CLOSED')], max_length=5)),
                ('timestamp', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
